# Fetch the battery level from the peripheral half and expose both over BLE
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Idle after 1min, deep sleep after 1h
CONFIG_ZMK_SLEEP=y
CONFIG_PM_DEVICE=y
CONFIG_ZMK_IDLE_TIMEOUT=60000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Enable mouse (needed for the Mouse layer)
CONFIG_ZMK_POINTING=y
